name: arbmkg_sli
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  webview_flutter: ^4.5.0
  webview_flutter_android: ^3.16.1
  flutter_native_splash: ^2.4.6
  audioplayers: ^6.4.0
  provider: ^6.0.5
  video_player: ^2.7.0
  chewie: ^1.4.0
  connectivity_plus: ^5.0.2
  flutter_3d_controller: ^2.2.0
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/objects/
    - assets/buttons/Alat Ukur Cuaca/
    - assets/buttons/Fisis/
    - assets/buttons/Iklim/
    - assets/music.mp3
    - assets/buttons/Menu Utama/
    - assets/images/
    - assets/icons/playButton.svg
    - assets/icons/Setting.svg
    - assets/icons/SmallLogo.svg

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/FiraSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraSans-Medium.ttf
          weight: 500
    - family: AlumniSans
      fonts:
        - asset: assets/fonts/AlumniSans-ExtraBold.ttf
          weight: 800

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/BMKGLogo.png
  android_12:
    image: assets/images/BMKGLogo.png
    icon_background_color: "#ffffff"
  web: false
